import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "16px",
    width: "100%",
    marginBottom: "40px",
  },
  card: {
    position: "relative",
    background: "var(--kpi-card-bg)",
    borderRadius: "12px",
    border: "1px solid var(--kpi-card-border)",
    boxShadow: "var(--shadow-card)",
    padding: "20px 18px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    transition: "transform 0.2s ease, box-shadow 0.2s ease, background-color 0.3s ease, border-color 0.3s ease",
    cursor: "default",
    overflow: "hidden",
  },
  headerRow: { display: "flex", alignItems: "center", gap: "10px", marginBottom: "6px" },
  iconBox: { width: "36px", height: "36px", borderRadius: "9px", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  labelGroup: { display: "flex", alignItems: "center", gap: "5px" },
  label: { fontSize: "13px", color: "var(--kpi-label-color)", fontWeight: 500, whiteSpace: "nowrap" },
  value: { fontSize: "26px", fontWeight: 700, color: "var(--kpi-value-color)", letterSpacing: "-0.5px", lineHeight: 1.2, margin: "4px 0" },
  badge: { display: "inline-flex", alignItems: "center", gap: "3px", padding: "4px 8px", borderRadius: "6px", width: "fit-content", marginTop: "4px" },
  skeleton: { background: "linear-gradient(90deg, var(--skeleton-from) 25%, var(--skeleton-mid) 50%, var(--skeleton-to) 75%)", backgroundSize: "200% 100%", animation: "shimmer 1.5s infinite", borderRadius: "6px" },
  modalBackdrop: { position: "fixed", inset: 0, background: "rgba(15, 23, 42, 0.45)", zIndex: 1000, display: "flex", alignItems: "center", justifyContent: "center", padding: 24 },
  modalPanel: { background: "#fff", borderRadius: 16, maxWidth: 480, width: "100%", maxHeight: "min(80vh, 520px)", overflow: "auto", padding: "20px 22px", boxShadow: "0 25px 50px rgba(0,0,0,0.15)" },
  modalHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16 },
  modalTitle: { margin: 0, fontSize: 18, fontWeight: 700, color: "#0F172A" },
  modalClose: { border: "none", background: "transparent", fontSize: 24, lineHeight: 1, cursor: "pointer", color: "#64748B", padding: "0 4px" },
  alertList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 12 },
  alertItem: { border: "1px solid #E2E8F0", borderRadius: 10, padding: "12px 14px" },
  alertTop: { display: "flex", alignItems: "center", gap: 8, marginBottom: 8, flexWrap: "wrap" },
  sevPill: { fontSize: 11, fontWeight: 700, padding: "2px 8px", borderRadius: 6 },
  alertMessage: { margin: 0, fontSize: 14, color: "#1E293B", lineHeight: 1.45 },
  alertMeta: { margin: "8px 0 0", fontSize: 11, color: "#94A3B8" },
};